/**
 * Edition version — single source of truth for the annotated book edition.
 *
 * Change EDITION / ANNOTATIONS_CREDIT here; builds and the preview server
 * propagate them to: cover, spine, title page, colophon, home hero, review
 * chrome, and (via syncEditionInHtml) any stale built HTML still on disk.
 */
export const EDITION = 'v0.3.4';

/**
 * Annotations credit — which models authored / revised the commentary.
 */
export const ANNOTATIONS_CREDIT =
  'Annotations by Claude Sonnet 4.6 (Revised by Opus 4.6, GPT 5.6 Sol, Grok 4.5)';

/** Cache-bust / equality key for preview + review shells. */
export function editionKey(edition = EDITION, credit = ANNOTATIONS_CREDIT) {
  return `${edition}\0${credit}`;
}

/**
 * Rewrite edition + annotations-credit strings in HTML so stale builds
 * (title page, colophon, cover fragments, home placeholders) match the
 * current edition.mjs values without requiring a full rebuild.
 */
export function syncEditionInHtml(
  html,
  { edition = EDITION, credit = ANNOTATIONS_CREDIT } = {},
) {
  if (!html) return html;
  let out = html;

  // "Annotated edition — v0.2 beta" (banner / label / back cover lead)
  out = out.replace(
    /Annotated edition — [^\s.<][^<]*?(?=\.?<\/|\.(?:\s|&nbsp;|<))/g,
    `Annotated edition — ${edition}`,
  );

  // Colophon: "Book edition: v0.2 beta."
  out = out.replace(
    /Book edition:\s*[^\s.<][^<]*?(?=\.?<\/|\.(?:\s|&nbsp;|<))/g,
    `Book edition: ${edition}`,
  );

  // Spine version span
  out = out.replace(
    /(<span class="spine-version">)[\s\S]*?(<\/span>)/g,
    `$1${edition}$2`,
  );

  // Dedicated credit elements
  out = out.replace(
    /(<p class="annotations-credit">)[\s\S]*?(<\/p>)/g,
    `$1${credit}$2`,
  );
  out = out.replace(
    /(<span class="hero-credit">)[\s\S]*?(<\/span>)/g,
    `$1${credit}$2`,
  );
  out = out.replace(
    /(<span class="hero-edition">)[\s\S]*?(<\/span>)/g,
    `$1Annotated edition — ${edition}$2`,
  );

  // Review chrome (if a cached shell still has an old value)
  out = out.replace(
    /(Content review · )[^<]+/g,
    `$1${edition}`,
  );
  out = out.replace(
    /(source live from YAML · )[^<]+/g,
    `$1${edition}`,
  );
  out = out.replace(
    /(line notes in source chapters · )[\s\S]*?(\. Edit)/g,
    `$1${credit}$2`,
  );

  // Colophon Credits paragraph (legacy prose or ANNOTATIONS_CREDIT sentence)
  out = out.replace(
    /Annotations were initially generated by Claude Sonnet 4\.6[^<]*?(?=\s*Publisher mark)/g,
    `${credit}. `,
  );
  out = out.replace(
    /(<strong>Credits\.<\/strong>\s*)Annotations by Claude Sonnet 4\.6[^<]*?(?=\s*Publisher mark)/g,
    `$1${credit}. `,
  );

  return out;
}
